import type { Task, QuickLink, Nationality } from "./types"

export const degrees = [
  "Arts (BA)",
  "Business Studies (BComm)",
  "Computer Science (BSc)",
  "Data Science (BSc)",
  "Engineering (BE)",
  "Law (BCL)",
  "Medicine (MB BCh BAO)",
  "Nursing (BSc)",
  "Science (BSc)",
  "Biomedical Science (BSc)",
  "Marine Science (BSc)",
  "Psychology (BA)",
  "Economics (BA)",
  "Mathematics (BSc)",
  "Physics (BSc)",
  "Chemistry (BSc)",
  "Biotechnology (BSc)",
  "Software Engineering (BSc)",
  "Electrical Engineering (BE)",
  "Civil Engineering (BE)",
  "Mechanical Engineering (BE)",
  "Environmental Science (BSc)",
  "Pharmacy (BSc)",
  "Dentistry (BDS)",
  "Physiotherapy (BSc)",
  "Occupational Therapy (BSc)",
  "Speech and Language Therapy (BSc)",
]

export const mandatoryTasks: Task[] = [
  {
    id: "1",
    title: "Register for IRP (Irish Residence Permit)",
    description: "Book an appointment and register with immigration. Required within 90 days of arrival.",
    category: "irp",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["non-eu"],
    link: "https://burghquayregistrationoffice.inis.gov.ie/",
    dueDate: "90 days after arrival",
  },
  {
    id: "2",
    title: "Complete University Registration",
    description: "Complete your online registration on the student portal and upload required documents.",
    category: "registration",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["eu", "non-eu", "usa"],
    link: "https://www.universityofgalway.ie/registration/",
  },
  {
    id: "3",
    title: "Pay Tuition Fees",
    description: "Pay your tuition fees or set up a payment plan through the fees office.",
    category: "fees",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["eu", "non-eu", "usa"],
    link: "https://www.universityofgalway.ie/fees/",
  },
  {
    id: "4",
    title: "Get Student Leap Card",
    description: "Apply for a Student Leap Card for discounted public transport across Ireland.",
    category: "other",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["eu", "non-eu", "usa"],
    link: "https://www.leapcard.ie/en/Home.aspx",
  },
  {
    id: "5",
    title: "Open Irish Bank Account",
    description: "Open a bank account with AIB, Bank of Ireland, or other Irish banks.",
    category: "bank",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["non-eu", "usa"],
    link: "https://aib.ie/our-products/current-accounts/student-plus",
  },
  {
    id: "6",
    title: "Apply for PPS Number",
    description: "Required for employment and some government services in Ireland.",
    category: "pps",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["eu", "non-eu", "usa"],
    link: "https://www.gov.ie/en/service/12e6de-get-a-personal-public-service-pps-number/",
  },
  {
    id: "7",
    title: "Register with Global Galway",
    description: "Connect with the international student office for support and events.",
    category: "other",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["non-eu", "usa"],
    link: "https://www.universityofgalway.ie/international-affairs/",
  },
  {
    id: "8",
    title: "Attend Orientation Week",
    description: "Participate in orientation activities to learn about campus and student life.",
    category: "other",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["eu", "non-eu", "usa"],
  },
  {
    id: "9",
    title: "Set Up Student Email",
    description: "Activate your University of Galway email account for official communications.",
    category: "registration",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["eu", "non-eu", "usa"],
    link: "https://www.universityofgalway.ie/information-solutions-services/",
  },
  {
    id: "10",
    title: "Get Student ID Card",
    description: "Collect your student ID card from the registration office.",
    category: "registration",
    isMandatory: true,
    isCompleted: false,
    applicableNationalities: ["eu", "non-eu", "usa"],
  },
]

export const quickLinks: QuickLink[] = [
  {
    id: "1",
    title: "Student Portal",
    description: "Access your academic records, timetable, and more",
    url: "https://www.universityofgalway.ie/student-portal/",
    icon: "GraduationCap",
  },
  {
    id: "2",
    title: "Registration",
    description: "Complete your university registration",
    url: "https://www.universityofgalway.ie/registration/",
    icon: "ClipboardCheck",
  },
  {
    id: "3",
    title: "Global Galway",
    description: "International student support and services",
    url: "https://www.universityofgalway.ie/international-affairs/",
    icon: "Globe",
  },
  {
    id: "4",
    title: "Fees & Funding",
    description: "Tuition fees, payment plans, and scholarships",
    url: "https://www.universityofgalway.ie/fees/",
    icon: "CreditCard",
  },
  {
    id: "5",
    title: "Career Connect",
    description: "Career services, internships, and job opportunities",
    url: "https://www.universityofgalway.ie/careers/",
    icon: "Briefcase",
  },
  {
    id: "6",
    title: "Societies",
    description: "Join clubs and societies",
    url: "https://www.societies.nuigalway.ie/",
    icon: "Users",
  },
  {
    id: "7",
    title: "Library",
    description: "Access library resources and study spaces",
    url: "https://library.universityofgalway.ie/",
    icon: "BookOpen",
  },
  {
    id: "8",
    title: "Accommodation",
    description: "Find student housing and accommodation",
    url: "https://www.universityofgalway.ie/accommodation/",
    icon: "Home",
  },
]

export function getTasksForNationality(nationality: Nationality): Task[] {
  return mandatoryTasks.filter((task) => task.applicableNationalities.includes(nationality))
}
